First commit for React.
rabdulin/yard-frontend pull request #3
Opened 2017-07-07 13:29 UTC by rabdulin

2017-07-07 17:07 UTC, imevro requested changes

2017-07-07 17:07 UTC, evgenyrodionov commented on public/index.html
> +    <title>React App</title>
читай чужие пры

2017-07-07 17:07 UTC, evgenyrodionov commented on src/Complexes/List/Banner.js
> +      <Row center="xs">
и поставь преттир

2017-07-07 21:35 UTC, imevro requested changes

2017-07-07 21:35 UTC, evgenyrodionov commented on .vscode/settings.json
> +// Поместите параметры в этот файл, чтобы перезаписать параметры по умолчанию и пользовательские параметры.
В гитигнор всю директорию

2017-07-07 21:35 UTC, evgenyrodionov commented on public/manifest.json
> +  "short_name": "React App",
читай чужие пры

2017-07-08 10:08 UTC, imevro requested changes

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +    <a className="complex-card">
поставь преттир

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/List/complexes.html
>    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300,400,700" rel="stylesheet">
зачем этот файл вообще

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/Show/Amenities.js
> +            <AmenityProps>Бассейн</AmenityProps>
Почему аменитипропс?

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/Show/Amenities.js
> +import AmenityProps from "./AmenityProps.js";
.джс можно опустить

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/Show/Characters.js
> +              <dt className="complex-characters-key">Количество квартир:</dt>
нужно объединять дт и дд, а не разносить по колонкам (тем более что тут не по 2 колонки)

2017-07-08 10:08 UTC, evgenyrodionov commented on src/Complexes/Show/Geo.js
> +              <GeoProps place="Красный Октябрь" distance="24 минуты, 6 км" />
почему постфикс пропс? Я не понимаю

2017-07-08 10:08 UTC, evgenyrodionov commented on src/complex.html
> +<!DOCTYPE html>
зачем ты хтмл оставил

2017-07-08 12:23 UTC, rabdulin commented on src/Complexes/List/complexes.html
>    <link href="https://fonts.googleapis.com/css?family=Fira+Sans:300,400,700" rel="stylesheet">
Понимаю, что не нужен. Использовал для сравнения того, что получилось с тем, что было.

2017-07-08 12:23 UTC, rabdulin commented on src/Complexes/Show/Amenities.js
> +import AmenityProps from "./AmenityProps.js";
Да, это случайно

2017-07-08 17:24 UTC, imevro requested changes

2017-07-08 17:24 UTC, evgenyrodionov commented on src/Complexes/Show/Summary.js
> +import Sum from "./Sum";
Сумма?

2017-07-08 17:24 UTC, evgenyrodionov commented on src/Complexes/List/Card.js
> +    <a className="complex-card">
ну и че?

2017-07-08 21:44 UTC, imevro approved these changes

2017-07-09 22:15 UTC, merged