Eslint
rabdulin/yard-frontend pull request #5
Opened 2017-07-14 21:26 UTC by rabdulin

https://yard-frontend-xluchmnmga.now.sh/

2017-07-14 23:42 UTC, evgenyrodionov commented
Коммиты суперхуевейшие

2017-07-14 23:44 UTC, imevro requested changes
и твой деплой не открывается

2017-07-14 23:44 UTC, evgenyrodionov commented on .eslintrc.json
> +    "linebreak-style": 0,
отключаем правила только по согласованию со мной

2017-07-14 23:44 UTC, evgenyrodionov commented on package.json
> +	"lint": "./node_modules/.bin/eslint --ext js --ext jsx src/",
можно опустить `./node_modules/.bin/`, если ты напишешь `eslint ...`, то нпм/ярн сами полезут в директорию `./node_modules/.bin/` выполнить этот файл

2017-07-14 23:45 UTC, evgenyrodionov commented
Ты задеплоил неправильно, надо деплоить директорию билд, а не весь проект, потому что если ты деплоишь просто как `now`, то zeit (он же now) запускает `npm run start`, а это ваще-то вебпаковский сервер, который нужен для разработки. Мы билдим наше приложение и деплоим уже статику

2017-07-15 13:16 UTC, rabdulin commented
https://yard-frontend-zidhubecpv.now.sh/

2017-07-15 13:32 UTC, imevro requested changes
в чате дал комментарии

2017-07-15 21:11 UTC, evgenyrodionov commented
Где новый деплой?

2017-07-15 21:18 UTC, rabdulin commented
https://yard-frontend-fgxhphmeag.now.sh/

2017-07-15 21:23 UTC, merged

2017-07-15 21:24 UTC, evgenyrodionov commented
Не забудь сделать `git pull origin master --rebase` в своем бранче